// pages/symmetry/MinoList.tsx
import { css } from "@emotion/react"
import { getMinoColor } from "components/graph"
import { Polyomino } from "mino"
import MinoLink from "components/MinoLink"

export default function MinoList({ minos }: { minos: Polyomino[][] }) {
  return (
    <div
      css={css`
        display: flex;
        flex-wrap: wrap;
        gap: 1.75rem 1.75rem;
      `}
    >
      {minos.map((minos, gen) => {
        return (
          <div
            key={gen}
            css={css`
              display: flex;
              gap: 0.75rem;
            `}
          >
            {gen}
            <div
              css={css`
                display: flex;
                align-items: center;
                flex-wrap: wrap;
                gap: 0.75rem;
                justify-content: space-between;

                ::after {
                  content: "";
                  flex: auto;
                }
              `}
            >
              {minos.map((mino) => {
                const { stroke, fill } = getMinoColor(mino)
                return (
                  <MinoLink
                    to={`/catalog/${mino.toString()}`}
                    key={mino.data}
                    mino={mino}
                    size={8}
                    fill={fill}
                    stroke={stroke}
                  />
                )
              })}
            </div>
          </div>
        )
      })}
    </div>
  )
}

// src/routes/(nav)/intro/MinoList.svelte
<script lang="ts">
  import { getMinoColor } from "$lib/components/graph"
  import MinoLink from "$lib/components/MinoLink.svelte"
  import { Polyomino } from "$lib/mino"

  const minos = [
    "1",
    "01_11",
    "010_111",
    "101_111",
    "110_101_111",
    "0010_1110_0111_0100",
  ]
</script>

<div class="mino-list">
  {#each minos as minoStr}
    {@const mino = Polyomino.fromString(minoStr)}
    {@const { stroke, fill } = getMinoColor(mino)}
    <MinoLink
      {mino}
      href={`catalog/${mino.transform.free()}`}
      size={15}
      --stroke={stroke}
      --fill={fill}
    />
  {/each}
</div>

<style>
  .mino-list {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    justify-content: center;
    gap: 1rem;
  }

  @media (min-width: 40rem) {
    .mino-list {
      gap: 2rem;
    }
  }
</style>
