// src/routes/(nav)/symmetry/SymmetryMino.svelte
<script lang="ts">
  import { getMinoColor } from "$lib/components/graph"
  import MinoLink from "$lib/components/MinoLink.svelte"
  import SymmetryMarkers from "$lib/components/SymmetryMarkers.svelte"
  import type { Polyomino } from "$lib/mino"

  interface Props {
    mino: Polyomino
    size: number
  }

  const { mino, size }: Props = $props()
  const { stroke, fill } = $derived(getMinoColor(mino))
</script>

<div class="wrapper">
  <MinoLink
    href="/catalog/{mino.toString()}"
    {mino}
    {size}
    --fill={fill}
    --stroke={stroke}
    gridStyle="thin"
  >
    <SymmetryMarkers {mino} {size} stroke-width={2} stroke="#ffffffaa" />
  </MinoLink>
</div>

<style>
  .wrapper :global(svg) {
    overflow: visible;
  }
</style>

// pages/symmetry/SymmetryMino.tsx
import { css } from "@emotion/react"
import { getMinoColor } from "components/graph"
import MinoLink from "components/MinoLink"
import SymmetryMarkers from "components/SymmetryMarkers"
import { Polyomino } from "mino"

interface Props {
  mino: Polyomino
  size: number
}
export default function SymmetryMino({ mino, size }: Props) {
  const { stroke, fill } = getMinoColor(mino)
  return (
    <div
      css={css`
        svg {
          overflow: visible;
      `}
    >
      <MinoLink
        to={`/catalog/${mino.toString()}`}
        mino={mino}
        size={size}
        fill={fill}
        stroke={stroke}
        gridStyle="thin"
      >
        {
          <SymmetryMarkers
            mino={mino}
            size={size}
            strokeWidth={2}
            stroke={"#ffffffaa"}
          />
        }
      </MinoLink>
    </div>
  )
}
