// src/lib/components/Compass/Compass.svelte
<script lang="ts">
  import G from "../svg/G.svelte"
  import AlterableMino from "./AlterableMino.svelte"
  import CompassBackground from "./CompassBackground.svelte"
  import CompassLinks from "./CompassLinks.svelte"
  import { CompassContext, setCompassContext, svgSize } from "./helpers.svelte"
  import SymmetryRing from "./SymmetryRing.svelte"

  let { selected = $bindable() } = $props()
  let showEditable = $state(false)

  let context = new CompassContext()
  setCompassContext(context)
</script>

<svg viewBox="{-svgSize} {-svgSize} {svgSize * 2} {svgSize * 2}">
  <G>
    <CompassBackground />
    <CompassLinks bind:mino={selected} />
    <G
      onhover={(hovered) => {
        showEditable = hovered
      }}
    >
      <SymmetryRing bind:mino={selected} />
      <AlterableMino highlight={showEditable} bind:mino={selected} />
    </G>
  </G>
</svg>

<style>
  svg {
    width: 22rem;
    height: 22rem;
    pointer-events: none;
  }
</style>

// src/app/Compass/Compass.tsx
import React from "react"
import { css } from "emotion"
import { RelativeLink } from "mino"

import { useSelected } from "app/SelectedContext"
import CompassLinks from "./CompassLinks"
import Background from "./CompassBackground"
import AdjustableMino from "./AdjustableMino"
import SymmetryRing from "./SymmetryRing"
import { svgSize } from "./compassHelpers"

/**
 * Displays a mino and its direct children and parents.
 */
export default function Compass() {
  // true if the inner symmetry ring has hover focus
  const [showEditable, setShowEditable] = React.useState(false)
  // the currently selected relative mino
  const [hovered, setHovered] = React.useState<RelativeLink | undefined>()

  // Don't render the compass if there is no mino selected
  const selected = useSelected()
  if (!selected) return null

  return (
    <svg
      viewBox={`${-svgSize} ${-svgSize} ${svgSize * 2} ${svgSize * 2}`}
      className={css`
        width: 22rem;
        height: 22rem;
        pointer-events: none;
      `}
    >
      <Background />
      <CompassLinks hovered={hovered} onHover={setHovered} />
      <SymmetryRing onHover={setShowEditable} />
      <AdjustableMino
        onHover={setHovered}
        hovered={hovered}
        showEditable={showEditable}
      />
    </svg>
  )
}
