// src/lib/components/Compass/ReflectionAxes.svelte
<script module lang="ts">
  export const reflectionOrder = [
    "flipVert",
    "flipMainDiag",
    "flipHoriz",
    "flipMinorDiag",
  ] as const
</script>

<script lang="ts">
  import { getSymmetryColor } from "../graph"

  import { svgTransform } from "../svg"
  import Line from "../svg/Line.svelte"
  import { colors } from "../theme"
  import {
    getCompassContext,
    innerRingRadius as radius,
  } from "./helpers.svelte"

  const { mino } = $props()
  const color = $derived(getSymmetryColor(mino.transform.symmetry()))
  const context = $derived(getCompassContext())
</script>

<g opacity={2 / 3}>
  {#each reflectionOrder as reflection, i}
    {@const isHovered = reflection === context.transform}
    {#if mino.transform.hasSymmetry(reflection) || isHovered}
      <Line
        p1={[-radius, 0]}
        p2={[radius, 0]}
        stroke={isHovered ? colors.highlight : color}
        stroke-width={isHovered ? 4 : 2}
        transform={svgTransform().rotate(45 * i)}
      />
    {/if}
  {/each}
</g>

// src/app/Compass/ReflectionAxes.tsx
import React from "react"

import { Line, svgTransform } from "app/svg"
import { colors } from "style/theme"
import {
  TransformCtx,
  innerRingRadius as radius,
  useSelected,
  useSelectedColor,
} from "./compassHelpers"

export const reflectionOrder = [
  "flipVert",
  "flipMainDiag",
  "flipHoriz",
  "flipMinorDiag",
] as const

/**
 * Displays a line corresponding to the axes of the mino
 */
export default function ReflectionAxes() {
  const mino = useSelected()
  const color = useSelectedColor()
  const selectedTrans = TransformCtx.useValue()
  return (
    <g opacity={2 / 3}>
      {reflectionOrder.map((reflection, i) => {
        const isHovered = reflection === selectedTrans
        return (
          (mino.transform.hasSymmetry(reflection) || isHovered) && (
            <Line
              key={i}
              p1={[-radius, 0]}
              p2={[radius, 0]}
              stroke={isHovered ? colors.highlight : color}
              strokeWidth={isHovered ? 4 : 2}
              transform={svgTransform().rotate(45 * i)}
            />
          )
        )
      })}
    </g>
  )
}
