// src/lib/components/Compass/TransformButtons.svelte
<script lang="ts">
  import { type Transform } from "$lib/mino"
  import { getSymmetryColor } from "../graph"
  import { svgTransform, SVGTransform } from "../svgUtils"
  import { onHover } from "../svgUtils"
  import { getCompassContext, innerRingRadius } from "./helpers.svelte"
  import { reflectionOrder } from "./ReflectionAxes.svelte"

  const radius = innerRingRadius + 7.5

  // TODO replace these icons with actual SVG
  const rotationSymbols = {
    rotateRight: "⃕",
    rotateHalf: "↻",
    rotateLeft: "⃔",
  }

  let { visible, mino = $bindable() } = $props()
  const context = $derived(getCompassContext())
  const color = $derived(getSymmetryColor(mino.transform.symmetry()))
</script>

<g class="buttons" opacity={visible ? 1 : 0}>
  {#each reflectionOrder as trans, i}
    {@render button(
      "↕︎",
      trans,
      svgTransform()
        .translate(radius, 0)
        .rotate(45 * i),
    )}
  {/each}
  {#each ["rotateLeft", "rotateHalf", "rotateRight"] as const as trans, i}
    {@render button(
      rotationSymbols[trans],
      trans,
      svgTransform()
        .translate(0, -radius)
        .rotate(30 * (i - 1)),
      trans === "rotateHalf" ? "rotate-half" : "rotate",
    )}
  {/each}
</g>

{#snippet button(
  icon: string,
  trans: Transform,
  svgTrans: SVGTransform,
  cls?: string,
)}
  <text
    class={["text", cls]}
    fill={color}
    onclick={() => (mino = mino.transform.apply(trans))}
    {...onHover((hovered) => (context.transform = hovered ? trans : undefined))}
    transform={svgTrans.toString()}
  >
    {icon}
  </text>
{/snippet}

<style>
  .buttons {
    transition: opacity 100ms ease-in-out;
  }

  .buttons .text {
    cursor: pointer;
    text-anchor: middle;
    pointer-events: initial;
    user-select: none;
    dominant-baseline: middle;
  }
  .buttons .text:hover {
    fill: var(--color-highlight);
  }

  .buttons .rotate {
    font-size: 20px;
    dominant-baseline: middle;
  }
  .buttons .rotate-half {
    font-size: 20px;
    dominant-baseline: initial;
  }
</style>

// src/app/Compass/TransformButtons.tsx
import React from "react"
import { css } from "@emotion/css"

import { Transform } from "mino"
import { colors } from "style/theme"
import { SVGTransform, svgTransform, Text } from "app/svg"
import { useSetSelected } from "app/SelectedContext"
import {
  TransformCtx,
  innerRingRadius,
  useSelected,
  useSelectedColor,
} from "./compassHelpers"

import { reflectionOrder } from "./ReflectionAxes"
const radius = innerRingRadius + 5

// TODO replace these icons with actual SVG
const rotationSymbols = {
  rotateRight: "⃕",
  rotateHalf: "↻",
  rotateLeft: "⃔",
}

interface ButtonProps {
  icon: string
  trans: Transform
  svgTrans: SVGTransform
  className?: string
}

function Button({ icon, trans, svgTrans, className }: ButtonProps) {
  const mino = useSelected()
  const color = useSelectedColor()
  const setSelected = useSetSelected()
  const setTransform = TransformCtx.useSetValue()

  return (
    <Text
      className={css`
        cursor: pointer;
        fill: ${color};
        pointer-events: initial;
        user-select: none;
        dominant-baseline: middle;
        :hover {
          fill: ${colors.highlight};
        }
        ${className}
      `}
      onClick={() => setSelected(mino.transform(trans))}
      onHover={(hovered) => setTransform(hovered ? trans : null)}
      transform={svgTrans}
    >
      {icon}
    </Text>
  )
}

interface Props {
  visible?: boolean
}

/**
 * Buttons that can be used to transform the mino into one of its reflections/rotations
 */
export default function TransformButtons({ visible }: Props) {
  return (
    <g
      className={css`
        transition: opacity 100ms ease-in-out;
        opacity: ${visible ? 1 : 0};
      `}
    >
      {reflectionOrder.map((trans, i) => (
        <Button
          key={trans}
          icon="↕︎"
          trans={trans}
          svgTrans={svgTransform()
            .translate(radius, 0)
            .rotate(45 * i)}
        />
      ))}
      {(["rotateLeft", "rotateHalf", "rotateRight"] as const).map(
        (trans, i) => (
          <Button
            key={trans}
            icon={rotationSymbols[trans]}
            trans={trans}
            className={css`
              font-size: 20px;
              text-anchor: middle;
              dominant-baseline: ${trans === "rotateHalf"
                ? "initial"
                : "middle"};
            `}
            svgTrans={svgTransform()
              .translate(0, -radius)
              .rotate(30 * (i - 1))}
          />
        ),
      )}
    </g>
  )
}
