// components/Compass/AlterableMino.tsx
import { css } from "@emotion/react"
import tinycolor from "tinycolor2"

import { O_OCTOMINO } from "mino"
import { NUM_GENERATIONS, getMinoColor } from "components/graph"
import { colors } from "style/theme"
import { useSelected } from "./compassHelpers"
import MinoSquare, { Hole } from "./SelectableSquare"

interface Props {
  highlight?: boolean
}

// TODO (static css) change this to be static
/** The squares of the mino, highlighting parent squares */
function InnerSquares({ highlight }: Props) {
  const mino = useSelected()
  const { fill, stroke } = getMinoColor(mino)

  return (
    <g key={mino.data}>
      {mino.equals(O_OCTOMINO) && <Hole />}
      {mino.relatives.possibleParents().map((link, i) => (
        <MinoSquare
          key={i}
          link={link as any}
          defaultCss={css`
            fill: ${!!link.mino && highlight
              ? tinycolor.mix(fill, "white", 25).toString()
              : fill};
            stroke: ${stroke};
          `}
          selectedCss={css`
            fill: ${tinycolor.mix(fill, "white", 80).toString()};
          `}
        />
      ))}
    </g>
  )
}

/** All neighbors that can be turned into children */
function OuterSquares() {
  const mino = useSelected()
  // Don't render if on the last generation
  if (mino.order >= NUM_GENERATIONS) return null
  return (
    <g key={mino.data}>
      {mino.relatives.enumerateChildren().map((link, i) => (
        <MinoSquare
          key={i}
          link={link}
          defaultCss={css`
            fill: ${colors.highlight};
            stroke: gray;
            opacity: 0;

            @media (hover: none) {
              fill: ${colors.bg};
              stroke: grey;
              opacity: 0.25;
            }
          `}
          selectedCss={css`
            opacity: 0.5;
          `}
        />
      ))}
    </g>
  )
}

/**
 * A mino that can have squares added or removed from it.
 */
export default function AlterableMino({ highlight }: Props) {
  return (
    <g>
      <InnerSquares highlight={highlight} />
      <OuterSquares />
    </g>
  )
}

// src/lib/components/Compass/AlterableMino.svelte
<script lang="ts">
  import { O_OCTOMINO } from "$lib/mino"
  import Vector from "$lib/vector"
  import { getMinoColor, NUM_GENERATIONS } from "../graph"
  import { point } from "../svgUtils"
  import { colors } from "../theme"
  import { getMinoSizeAndTransform } from "./helpers.svelte"
  import SelectableSquare from "./SelectableSquare.svelte"

  let { highlight, mino = $bindable() } = $props()
  const { fill, stroke } = $derived(getMinoColor(mino))
</script>

<g>
  {#key mino}
    {#if mino.equals(O_OCTOMINO)}
      {@render hole()}
    {/if}
    {@render innerSquares(highlight)}
    {@render outerSquares()}
  {/key}
</g>

{#snippet innerSquares(highlight: boolean)}
  <g class="inner" class:highlight>
    {#each mino.relatives.possibleParents() as link}
      <SelectableSquare
        {link}
        bind:selected={mino}
        --fill={fill}
        --stroke={stroke}
      />
    {/each}
  </g>
{/snippet}

{#snippet outerSquares()}
  {#if mino.order < NUM_GENERATIONS}
    <g class="outer">
      {#each mino.relatives.enumerateChildren() as link}
        <SelectableSquare {link} bind:selected={mino} />
      {/each}
    </g>
  {/if}
{/snippet}

{#snippet hole()}
  {@const { size, transform } = getMinoSizeAndTransform(mino)}
  <rect
    {...point(transform(new Vector(1, 1)))}
    width={size}
    height={size}
    fill={colors.bg}
    stroke="none"
  />
{/snippet}

<style>
  .inner rect {
    fill: var(--fill);
    stroke: var(--stroke);
  }

  .inner.highlight rect[data-selectable="true"] {
    fill: color-mix(in oklch, var(--fill), white 20%);
  }

  .inner.highlight rect[data-selected="true"] {
    fill: color-mix(in oklch, var(--fill), white 80%);
  }

  .outer rect {
    stroke: grey;
    opacity: 0;
  }

  @media (hover: none) {
    .outer rect {
      stroke: grey;
      opacity: 0.5;
    }
  }

  .outer rect[data-selected="true"] {
    opacity: 0.5;
  }
</style>
