// src/lib/components/MinoList/MinoFilter/InputTitle.svelte
<script lang="ts">
  const { display, onclear } = $props()
</script>

<div class="container">
  {display}
  <button type="button" onclick={onclear}>clear</button>
</div>

<style>
  .container {
    font-size: 1.125rem;
    width: 100%;
    display: grid;
    grid-template-columns: 1fr 4rem;
  }

  button {
    /* TODO (refactor) factor out this button style */
    font-size: 1rem;
    font-family: serif;
    margin-left: 1rem;
    padding: 0;
    text-align: right;
    color: var(--color-fg);
    background: none;
    border: none;
    cursor: pointer;
  }
  button:hover {
    color: var(--color-highlight);
  }
</style>

// src/app/MinoList/MinoFilter/InputTitle.tsx
import React from "react"
import { css } from "@emotion/css"
import { colors } from "style/theme"

interface Props {
  display: string
  onClear(): void
}

/**
 * The display for a group of inputs
 */
export default function InputTitle({ display, onClear }: Props) {
  return (
    <div
      className={css`
        font-size: 1.125rem;
        width: 100%;
        display: grid;
        grid-template-columns: 1fr 4rem;
      `}
    >
      {display}
      <button
        type="button"
        onClick={onClear}
        className={css`
          /* TODO (refactor) factor out this button style */
          font-size: 1rem;
          font-family: serif;
          margin-left: 1rem;
          color: ${colors.fg};
          background: none;
          border: none;
          cursor: pointer;
          :hover {
            color: ${colors.highlight};
          }
        `}
      >
        clear
      </button>
    </div>
  )
}
