// src/app/FamilyTree/GenerationRings.tsx
import React, { memo, useMemo, useCallback } from "react"
import { Polyomino } from "mino"

import transition from "app/transition"
import { NUM_GENERATIONS, nodes, getMinoColor } from "app/graph"
import { useSelected } from "app/SelectedContext"
import SelectableMino from "app/SelectableMino"

import { START_GENS, getCoords } from "./treeHelpers"

const graphMinos = nodes.map((gen) =>
  gen.map((mino) => mino.transform.apply("flipMainDiag")),
)

function getBlockSize(gen: number) {
  return 2 + (NUM_GENERATIONS - gen) ** 2 / 2
}

interface MinoProps {
  mino: Polyomino
  gen: number
  selected?: Set<Polyomino>
  onHover?(mino: Polyomino): void
}

/**
 * Memoized wrapper around the mino to efficiently calculate it
 */
const RingMino = memo(function ({ mino, gen, selected, onHover }: MinoProps) {
  const coord = useMemo(() => getCoords(mino), [mino])
  return (
    <SelectableMino
      mino={mino}
      coord={coord}
      size={getBlockSize(gen)}
      selected={!!selected?.has(mino)}
      onHover={onHover}
      {...getMinoColor(mino)}
    />
  )
})

interface RingProps {
  minos: Polyomino[]
  gen: number
  skipAnimation: boolean
  selected?: Set<Polyomino>
  onHover?(mino: Polyomino): void
}

/**
 * A semicircle containing all the minos in a generation.
 */
const GenerationRing = memo(
  ({ minos, skipAnimation, ...minoProps }: RingProps) => {
    const [visIndex, setVisIndex] = React.useState(0)
    React.useEffect(() => {
      if (skipAnimation) {
        return
      }
      const trans = transition({
        duration: minos.length * 10,
        onUpdate(val) {
          setVisIndex(val * minos.length)
        },
      })
      return () => trans.cancel()
    }, [minos, skipAnimation])

    return (
      <>
        {minos.map((mino, i) => {
          return (
            (skipAnimation || i < visIndex) && (
              <RingMino key={mino.data} mino={mino} {...minoProps} />
            )
          )
        })}
      </>
    )
  },
)

export default function GenerationRings() {
  const selected = useSelected()

  // Split up the "selected" parent and child minos by generation for performance
  const getSelected = useCallback(
    (gen) => {
      const parents = selected
        ? selected.relatives.freeParents()
        : new Set<Polyomino>()
      const children = selected
        ? selected.relatives.freeChildren()
        : new Set<Polyomino>()
      if (!selected) return
      const selectedGen = selected.order
      if (gen === selectedGen) {
        return new Set([selected.transform.free()])
      } else if (gen === selectedGen - 1) {
        return parents
      } else if (gen === selectedGen + 1) {
        return children
      }
    },
    [selected],
  )

  return (
    <g>
      {graphMinos.map((minos, i) => {
        const gen = i + 1
        return (
          <GenerationRing
            minos={minos}
            gen={gen}
            key={gen}
            skipAnimation={gen <= START_GENS}
            selected={getSelected(gen)}
          />
        )
      })}
    </g>
  )
}

// src/routes/genealogy/GenerationRings.svelte
<script lang="ts">
  import { NUM_GENERATIONS, getMinoColor, nodes } from "$lib/components/graph"
  import SelectableMino from "$lib/components/SelectableMino.svelte"
  import type { Polyomino } from "$lib/mino"
  import { onMount } from "svelte"
  import { getCoords } from "./treeHelpers"
  import { fade } from "svelte/transition"

  interface Props {
    selected?: Polyomino
  }

  const graphMinos = nodes.map((gen) =>
    gen.map((mino) => mino.transform.apply("flipMainDiag")),
  )

  function getBlockSize(gen: number) {
    return 2 + (NUM_GENERATIONS - gen) ** 2 / 2
  }

  let { selected = $bindable() }: Props = $props()
  let visible = $state(false)

  onMount(() => {
    visible = true
  })
</script>

{#each graphMinos as minos, i}
  {@const gen = i + 1}
  {#if gen <= 6 || visible}
    <g in:fade>
      {#each minos as mino}
        {@const coord = getCoords(mino)}
        <SelectableMino
          {mino}
          {coord}
          size={getBlockSize(gen)}
          selected={selected?.transform.equivalent(mino)}
          {...getMinoColor(mino)}
          onselect={(_selected) => {
            selected = _selected
          }}
        />
      {/each}
    </g>
  {/if}
{/each}
