// src/lib/components/MinoList/MinoFilter/MinoFilter.svelte
<script lang="ts">
  import MdiFilter from "virtual:icons/mdi/filter"
  import ClassInput from "./ClassInput.svelte"
  import type { FilterOptions } from "./common"
  import SymmetryInput from "./SymmetryInput.svelte"
  import YesNoInputs from "./YesNoInputs.svelte"

  interface Props {
    value: FilterOptions
  }
  const {
    value = $bindable({ symmetries: [], classes: [], yesNo: {} }),
  }: Props = $props()
  let open = $state(false)
</script>

<details bind:open>
  <summary><MdiFilter /> {open ? "Hide" : "Show"} Filters</summary>
  <form>
    <SymmetryInput bind:value={value.symmetries} />
    <ClassInput bind:value={value.classes} />
    <YesNoInputs bind:value={value.yesNo} />
  </form>
</details>

<style>
  summary {
    color: var(--color-fg);
    background: none;
    border: none;
    font-family: serif;
    font-size: 1.125rem;
    margin-top: 2rem;
    margin-left: 2rem;
    cursor: pointer;
  }
  summary:hover {
    color: var(--color-highlight);
  }

  form {
    margin: 0 4rem;
    display: flex;
    flex-wrap: wrap;
    gap: 3rem;
  }
</style>

// components/MinoList/MinoFilter/MinoFilter.tsx
import { useState } from "react"
import { css } from "@emotion/react"
import { FaFilter } from "react-icons/fa"

import { colors } from "style/theme"
import SymmetryInput from "./SymmetryInput"
import ClassInput from "./ClassInput"
import YesNoInputs from "./YesNoInputs"
import { FilterOptions } from "./common"

interface Props {
  value: FilterOptions
  onUpdate(value: FilterOptions): void
}

function FilterForm({ value, onUpdate }: Props) {
  return (
    <form
      css={css`
        margin: 0 4rem;
        display: flex;
        flex-wrap: wrap;
        gap: 3rem;
      `}
    >
      <SymmetryInput
        value={value.symmetries}
        onUpdate={(val) => onUpdate({ ...value, symmetries: val })}
      />
      <ClassInput
        value={value.classes}
        onUpdate={(val) => onUpdate({ ...value, classes: val })}
      />
      <YesNoInputs
        onUpdate={(val) => onUpdate({ ...value, yesNo: val })}
        value={value.yesNo}
      />
    </form>
  )
}

/**
 * Collapsible filter for various properties of polyominoes.
 */
export default function MinoFilter(props: Props) {
  const [showFilter, setShowFilter] = useState(false)

  return (
    <div>
      {/* TODO (a11y) probably aria-expanded? */}
      <button
        css={css`
          color: ${colors.fg};
          text-align: right;
          background: none;
          border: none;
          font-family: serif;
          font-size: 1.125rem;
          margin-top: 2rem;
          margin-left: 2rem;
          cursor: pointer;
          :hover {
            color: ${colors.highlight};
          }
        `}
        onClick={() => setShowFilter((filter) => !filter)}
      >
        <FaFilter /> {showFilter ? "Hide" : "Show"} filters
      </button>
      {showFilter && <FilterForm {...props} />}
    </div>
  )
}
