// components/Breadcrumbs.tsx
import React from "react"
import Link from "next/link"
import { FaChevronRight } from "react-icons/fa"
import { css } from "@emotion/react"

interface Props {
  paths: CrumbPath[]
}

type CrumbPath = [name: string, url: string]

export default function Breadcrumbs({ paths }: Props) {
  return (
    <nav
      css={css`
        margin-bottom: 1rem;
        display: flex;
        gap: 0.5rem;
        align-items: center;

        a {
          text-decoration: none;
        }
      `}
    >
      <BreadcrumbPart paths={paths} />
    </nav>
  )
}

function BreadcrumbPart({ paths }: Props) {
  const [name, url] = paths[0]
  if (paths.length === 1) {
    return <Link href={url}>{name}</Link>
  }

  return (
    <>
      <Link href={url}>{name}</Link>
      <FaChevronRight />
      <BreadcrumbPart paths={paths.slice(1)} />
    </>
  )
}

// src/lib/components/Breadcrumbs.svelte
<script lang="ts">
  import type { Snippet } from "svelte"
  import MdiChevronRight from "virtual:icons/mdi/chevron-right"

  interface Props {
    paths: CrumbPath[]
  }

  type CrumbPath = [name: string | Snippet, url: string]

  const { paths }: Props = $props()
</script>

<nav>
  {@render breadcrumbPart(paths)}
</nav>

{#snippet breadcrumbPart(paths: CrumbPath[])}
  {const [name, url] = paths[0]}
  <a href={url}>
    {#if typeof name === "string"}
      {name}
    {:else}
      {@render name()}
    {/if}
  </a>
  {#if paths.length > 1}
    <MdiChevronRight />
    {@render breadcrumbPart(paths.slice(1))}
  {/if}
{/snippet}

<style>
  nav {
    margin-bottom: 1rem;
    display: flex;
    gap: 0.25rem;
    align-items: center;
  }

  a {
    text-decoration: none;
  }
</style>
