// components/MinoLink.tsx
import Link from "next/link"
import MinoDiv, { Props as MinoDivProps } from "components/MinoDiv"
import { css } from "@emotion/react"

interface Props extends Omit<MinoDivProps, "onClick"> {
  to: string
}

/**
 * A visual inline polyomino that links to another page.
 */
export default function MinoLink({ to, ...props }: Props) {
  return (
    <Link
      href={to}
      css={css`
        svg {
          transition: transform 150ms ease-in-out;
        }
        svg:hover {
          transform: scale(1.1);
        }
      `}
    >
      <MinoDiv {...props} />
    </Link>
  )
}

// src/lib/components/MinoLink.svelte
<script lang="ts">
  import MinoDiv, { type Props as MinoDivProps } from "./MinoDiv.svelte"

  interface Props extends Omit<MinoDivProps, "onClick"> {
    href: string
  }

  const { href, ...props }: Props = $props()
</script>

<a {href}>
  <MinoDiv {...props} />
</a>

<style>
  a :global(svg) {
    transition: transform 150ms ease-in-out;
  }
  a :global(svg:hover) {
    transform: scale(1.1);
  }
</style>
